// let num =[43,2,11,9,1];


//Classical For Loop

// for (let i=0;i<num.length;i++){
//     console.log(num[i]);
// }


//Squre Each element (For Each Loops) 

// num.forEach((element)=>{
//     console.log(element*element);
// })


// Array.Form 

// let name1="Aditya";
// let arr= Array.from(name1);

// console.log(arr);

let num =[43,2,11,9,1];


//  for ...of  (Short-Cut Way to Accessing Array : )

    // for (let i of num){
    //     console.log(i);
    // }


// For ... in 

     for (let i in num){
        console.log(i); // return Index
        console.log(num[i]);
     }